"""
Brush Training Processor - Modal Function
Trains Gaussian Splatting model using Brush.

Based on https://github.com/ArthurBrussee/brush
"""

import modal
import os
import json
import tempfile
import zipfile
from pathlib import Path

# Create Modal stub
stub = modal.Stub("brush-processor")

# Create image with Brush and dependencies
# Based on Brush's official Dockerfile
brush_image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install([
        "git",
        "build-essential",
        "cmake",
        "curl",
        "libglu1-mesa-dev",
        "freeglut3-dev",
        "mesa-common-dev",
        "pkg-config",
        "libssl-dev",
    ])
    # Install Rust
    .run_commands(
        "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y",
        "echo 'source $HOME/.cargo/env' >> $HOME/.bashrc",
    )
    # Clone and build Brush
    .run_commands(
        "git clone https://github.com/ArthurBrussee/brush.git /brush",
        "cd /brush && ~/.cargo/bin/cargo build --release",
    )
    # Install Python dependencies
    .pip_install([
        "torch==2.2.*",
        "torchvision==0.17.*",
        "numpy==1.26.*",
        "boto3==1.34.*",
        "plyfile==1.0.*",
    ])
)

@stub.function(
    image=brush_image,
    gpu="A10G",  # A10G for more VRAM needed for training
    timeout=7200,  # 2 hours timeout
    memory=49152,  # 48 GB RAM
    secrets=[modal.Secret.from_name("aws-s3-credentials")],
)
def train_gaussian_splatting(job_data: dict) -> dict:
    """
    Train Gaussian Splatting model using Brush

    Args:
        job_data: Dict with presentationId, stageId, inputFileKey

    Returns:
        Dict with outputKey and metadata
    """
    import boto3
    import subprocess

    presentation_id = job_data["presentationId"]
    stage_id = job_data["stageId"]
    input_file_key = job_data["inputFileKey"]  # COLMAP output ZIP

    # S3 configuration
    s3_bucket = os.environ["S3_BUCKET"]
    s3_client = boto3.client(
        "s3",
        aws_access_key_id=os.environ.get("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.environ.get("AWS_SECRET_ACCESS_KEY"),
        endpoint_url=os.environ.get("S3_ENDPOINT_URL"),
    )

    with tempfile.TemporaryDirectory() as tmpdir:
        # Download COLMAP data
        zip_path = os.path.join(tmpdir, "colmap.zip")
        print(f"Downloading COLMAP data from S3: {input_file_key}")
        s3_client.download_file(s3_bucket, input_file_key, zip_path)

        # Extract COLMAP data
        colmap_dir = os.path.join(tmpdir, "colmap")
        os.makedirs(colmap_dir, exist_ok=True)

        with zipfile.ZipFile(zip_path, 'r') as zipf:
            zipf.extractall(colmap_dir)

        # Create output directory
        output_dir = os.path.join(tmpdir, "output")
        os.makedirs(output_dir, exist_ok=True)

        # Run Brush training
        print("Running Brush training...")
        brush_cmd = [
            "/brush/target/release/brush",
            "train",
            "--data", colmap_dir,
            "--output", output_dir,
            "--iterations", "30000",  # Standard iteration count
            "--save-iterations", "7000,30000",  # Save checkpoints
        ]

        subprocess.run(brush_cmd, check=True)

        # Find output PLY file (Brush saves as point_cloud.ply)
        ply_files = list(Path(output_dir).glob("*.ply"))
        if not ply_files:
            raise ValueError("No PLY file generated by Brush")

        ply_path = str(ply_files[0])
        ply_size = os.path.getsize(ply_path)

        # Count vertices in PLY (approximate)
        with open(ply_path, 'rb') as f:
            content = f.read(10000)  # Read first 10KB
            # Look for "element vertex" line
            ply_vertices = 0
            for line in content.decode('utf-8', errors='ignore').split('\n'):
                if 'element vertex' in line:
                    ply_vertices = int(line.split()[-1])
                    break

        # Upload PLY to S3
        output_key = f"processed/{presentation_id}/brush_{stage_id}.ply"
        print(f"Uploading PLY to S3: {output_key}")
        s3_client.upload_file(ply_path, s3_bucket, output_key)

        return {
            "outputKey": output_key,
            "outputSize": ply_size,
            "metadata": {
                "plyVertices": ply_vertices,
                "iterations": 30000,
                "trainingCompleted": True,
            }
        }

@stub.local_entrypoint()
def main():
    """Local entrypoint for testing"""
    job_data = {
        "presentationId": "test-123",
        "stageId": "stage-789",
        "inputFileKey": "processed/test/colmap.zip"
    }

    result = train_gaussian_splatting.remote(job_data)
    print(json.dumps(result, indent=2))
